config/routes.rb
Guiav::Application.routes.draw do
  resources :users

  resources :laboratorios, path: "admin/laboratorios"
  resources :administradors

  post "/payment_notifications" => 'payment_notification#create'

  post "/valid_login" => "static_pages#login"
  get "static_pages/index"
  get "static_pages/index2"
  get "index/welcome"
  get "/about" => 'static_pages#about'
  get "/search" => 'search_medicaments#index'

  root 'static_pages#index2'

  resources :sessions, only: [:admin_login, :admin_create, :admin_destroy]
  controller :sessions do
    get 'admin/login' => :admin_login
    post 'admin/login' => :admin_create
    delete 'admin/logout' => :admin_destroy
    get 'admin/logout' => :admin_destroy
    post 'login' => :user_create
    get 'logout' => :user_destroy
  end

  controller :administrator_pages do
    get 'admin' => :home
  end

end

app/models/laboratorio.rb
class Laboratorio < ActiveRecord::Base
end

app/controllers/laboratorios_controller.rb
class LaboratoriosController < AdminController

  layout 'admin' # El layout es admin.html.erb

  before_action :set_laboratorio, only: [:show, :edit, :update, :destroy]

  # GET /laboratorios
  # GET /laboratorios.json
  def index
    @laboratorios = Laboratorio.all
  end

  # GET /laboratorios/1
  # GET /laboratorios/1.json
  def show
  end

  # GET /laboratorios/new
  def new
    @laboratorio = Laboratorio.new
  end

  # GET /laboratorios/1/edit
  def edit
  end

  # POST /laboratorios
  # POST /laboratorios.json
  def create
    @laboratorio = Laboratorio.new(laboratorio_params)

    respond_to do |format|
      if @laboratorio.save
        format.html { redirect_to @laboratorio, notice: 'Laboratorio was successfully created.' }
        format.json { render action: 'show', status: :created, location: @laboratorio }
      else
        format.html { render action: 'new' }
        format.json { render json: @laboratorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laboratorios/1
  # PATCH/PUT /laboratorios/1.json
  def update
    respond_to do |format|
      if @laboratorio.update(laboratorio_params)
        format.html { redirect_to @laboratorio, notice: 'Laboratorio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @laboratorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laboratorios/1
  # DELETE /laboratorios/1.json
  def destroy
    @laboratorio.destroy
    respond_to do |format|
      format.html { redirect_to laboratorios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laboratorio
      @laboratorio = Laboratorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laboratorio_params
      params.require(:laboratorio).permit(:nombre, :razon_social, :direccion, :departamento, :telefono, :web)
    end
end

app/helpers/laboratorios_helper.rb
module LaboratoriosHelper
end

app/views/laboratorios/_form.html.erb
<%= form_for(@laboratorio , class:"form-horizontal", role:"form") do |f| %>
  <% if @laboratorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@laboratorio.errors.count, "error") %> prohibited this laboratorio from being saved:</h2>

      <ul>
      <% @laboratorio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :nombre , class:"col-sm-2 control-label"%>
      <%= f.text_field :nombre, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :razon_social, class:"col-sm-2 control-label"   %>
      <%= f.text_field :razon_social, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :direccion , class:"col-sm-2 control-label"%> 
      <%= f.text_field :direccion, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :departamento, class:"col-sm-2 control-label"   %>
      <%= f.select :departamento, 
        ['Artigas',
          'Canelones',
          'Cerro',
          'Colonia',
          'Durazno',
          'Flores',
          'Florida',
          'Lavalleja',
          'Maldonado',
          'Montevideo',
          'Paysandú',
          'Rivera',
          'Rocha',
          'Río Negro',
          'Salto',
          'San José',
          'Soriano',
          'Tacuarembó',
          'Treinta y Tres'],
        { include_blank: true }, 
        {class: 'chz-select-departamento' }
      %>
    </div>
    <div class="form-group">
      <%= f.label :telefono, class:"col-sm-2 control-label" %>
      <%= f.text_field :telefono, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :web, class:"col-sm-2 control-label" %>
      <%= f.text_field :web , class:"form-control"%>
      </div>
    <div class="actions">
      <%= f.submit nil, class: "btn btn-primary"  %>
    </div>
<% end %>

app/views/laboratorios/edit.html.erb
<h1>Editing laboratorio</h1>

<%= render 'form' %>

<%= link_to 'Show', @laboratorio %> |
<%= link_to 'Back', laboratorios_path %>

app/views/laboratorios/index.html.erb
<div id="content-lab">
  <h1>Listado de laboratorios</h1>

  <div class="col-xs-6" >
      <div class="right-inner-addon">
          <i class="icon-search"></i>
          <input ng-model="search" type="search"
                 class="form-control" 
                 placeholder="Buscar" />
      </div>
  </div>
  <br><br><br>
  <div ng-controller="LaboratorioController as labCtrl">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Razon social</th>
          <th>Direccion</th>
          <th>Departamento</th>
          <th>Telefono</th>
          <th>Web</th>
          <th></th>
        </tr>
      </thead>

      <tbody >
          <tr ng-repeat="laboratorio in laboratorios | filter:search " ng-cloak>
            <td>{{ laboratorio.nombre }}</td>
            <td>{{ laboratorio.razon_social }}</td>
            <td>{{ laboratorio.direccion }}</td>
            <td>{{ laboratorio.departamento }}</td>
            <td>{{ laboratorio.telefono }}</td>
            <td>{{ laboratorio.web }}</td>
            <td>
              <a class="btn btn-xs btn-default" ng-href="/laboratorios/{{laboratorio.id}}/edit">Editar</a>
              <a class="btn btn-xs btn-danger" data-confirm="Estas seguro que desea eliminar el laboratorio?" data-method="delete" href="/laboratorios/{{laboratorio.id}}/" rel="nofollow">Eliminar</a>
            </td>
        </tr>
      </tbody>
    </table>
  </div>

  <br>
</div>

app/views/laboratorios/new.html.erb
<div id="content-lab">
	<h1>Ingresar laboratorio</h1>

	<%= render 'form' %>

	<%= link_to 'Atras', laboratorios_path %>

</div>

app/views/laboratorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @laboratorio.nombre %>
</p>

<p>
  <strong>Razon social:</strong>
  <%= @laboratorio.razon_social %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @laboratorio.direccion %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @laboratorio.departamento %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @laboratorio.telefono %>
</p>

<p>
  <strong>Web:</strong>
  <%= @laboratorio.web %>
</p>

<%= link_to 'Edit', edit_laboratorio_path(@laboratorio) %> |
<%= link_to 'Back', laboratorios_path %>