config/routes.rb
Guiav::Application.routes.draw do
  resources :users

  resources :laboratorios, path: "admin/laboratorios"
  resources :administradors

  post "/payment_notifications" => 'payment_notification#create'

  post "/valid_login" => "static_pages#login"
  get "static_pages/index"
  get "static_pages/index2"
  get "index/welcome"
  get "/about" => 'static_pages#about'
  get "/search" => 'search_medicaments#index'

  root 'static_pages#index2'

  resources :sessions, only: [:admin_login, :admin_create, :admin_destroy]
  controller :sessions do
    get 'admin/login' => :admin_login
    post 'admin/login' => :admin_create
    delete 'admin/logout' => :admin_destroy
    get 'admin/logout' => :admin_destroy
    post 'login' => :user_create
    get 'logout' => :user_destroy
  end

  controller :administrator_pages do
    get 'admin' => :home
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html ng-app="guiaV">
<head>
  <title>GuiaV</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'icon.ico' %>

  <!-- fonts -->
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>

</head>
<body>
	<div id="wrapper">
		<div id="header">
			<div id="navigation-bar">
				<nav class="navbar navbar-custom" role="navigation">
					<div class="container-fluid">
						<!-- Brand and toggle get grouped for better mobile display -->

						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav navbar-left">
								<li><%= image_tag "logochico.png" , height: '50' %></li>
							</ul>
							<ul class="nav navbar-nav">
								<li class="active"><a href="/admin/home">Admin</a></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Laboratorios <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><%= link_to "Nuevo Laboratorio", new_laboratorio_path %></li>
										<li><%= link_to "Ver Laboratorios", laboratorios_path %></li>
									</ul>
								</li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Categorias <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><%= link_to "Ingresar Categoria", new_laboratorio_path %></li>
										<li><%= link_to "Ver Categorias", laboratorios_path %></li>
									</ul>
								</li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Medicamentos <b class="caret"></b></a>
									<ul class="dropdown-menu">
										<li><%= link_to "Ingresar Medicamento", new_laboratorio_path %></li>
										<li><%= link_to "Ver Medicamentos", laboratorios_path %></li>
									</ul>
								</li>
							</ul>

							<ul class="nav navbar-nav navbar-right">
								<li><%= link_to "Cerrar Sesion", admin_logout_path, method: :delete %></li>
							</ul>
						</div><!-- /.navbar-collapse -->
					</div><!-- /.container-fluid -->
				</nav>
			</div>
		</div>
		<div id="wrapper-lab">
			<%= yield %>
		</div>
		
	</div>
	<div id="footer">
		
	</div>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="guiaV">
<head>
  <title>Guia V | Vademecum Veterinario</title>

  <meta name="description" content="Vademecum de especialidades veterinarias para grandes y pequeños animales">
	<meta name="keywords" content="vademecum, veterinario, uruguay">
	<meta property="og:url" content="http://www.guiav.com.uy/" />
	<meta property="og:image" content="http://www.guiav.com.uy/images/bookit.png" />
	<meta property="og:title" content="Guia V" />
	<meta property="og:description" content="Vademecum Veterinario" />

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'icon.ico' %>

  <!-- fonts -->
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="wrapper">
		<div id="header" class="home">
			<div class="header-nav">
				<ul>
					<% if current_user %>
						<li><a href=""><%= current_user.username %></a></li>
						<li><a href="/logout">Log out</a></li>
					<% else %>
						<li><a href="">Sign up</a></li>
						<li><a href="" data-toggle="modal" data-target="#signInModal">Log in</a></li>
					<% end %>
					<li><a href="">Help &nbsp;<i class="fa fa-angle-down"></i></a></li>
				</ul>
			</div>
			<div id="logo-header">
				<%= image_tag "logo.png" , height: '220' %>
			</div>
			<div id="licencia" ng-controller="SearchBoxController as searchCtrl">
				<form class="form-inline search" role="form">
				  <div class="form-group" >
				    <input type="text" class="form-control" style="width:600px;" id="exampleInputEmail2" placeholder="What are you looking for?" ng-model="search" >
				  </div>
				  <div class="form-group">
				    <button type="submit" class="btn btn-primary" style=" font-weight: bold;" ng-click="searchMedicament()">Search</button>
				  </div>
				 </form>
				<%= link_to 'Upgrade to GuiaV PRO Now', paypal_url, class: "btn btn-outline-inverse btn-lg", style: 'display: none' %> 
			</div>
			 
		</div>

		<!-- Modal -->
		<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" ng-controller="LogInController as loginCtrl">
		  <div class="modal-dialog">
		    <div class="modal-content">
		    	<form class="form-horizontal" role="form">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
		      </div>
		      <div class="modal-body">
		        <div ng-show="invalido" class="alert alert-danger">Usuario o contrasenia incorrecta</div>
		        <div ng-show="valido" class="alert alert-success">Bienvenido</div>
				  <div class="form-group">
				    <div class="col-sm-offset-1 col-sm-10" >
				      <input type="text" ng-model="username" class="form-control" id="inputEmail3" placeholder="Usuario">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-1 col-sm-10">
				      <input type="password" ng-model="password" class="form-control" id="inputPassword3" placeholder="Contraseña">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-2 col-sm-3">
				      <div class="checkbox">
				        <label>
				          <input type="checkbox" ng-model="remember"> Recordarme
				        </label>
				      </div>
				    </div>
				  </div>
				
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		        <button type="submit" class="btn btn-primary" ng-click="userValido()">Sign In</button>
		        
		      </div>
		      </form>
		    </div>
		  </div>
		</div>
	
		<%= yield %>

		<div id="footer" class="centered">

			<div id="footer-content">

				<h1 id="contact-us">CONTACTENOS</h1>
				<div id="map-canvas"></div>
				<div id="footer-bottom">
					<div id="logo-footer">
						<%= image_tag "logo_sin_texto.png" , height: '80' %>
					</div>
					<div id="contact">
							<ul>
								<li class="fbook">
									<a href="https://www.facebook.com/guiavet" target="_blank"><i class="fa fa-facebook fa-1x">

									</i></a>
								</li>
								<li class="mail"><a href="mailto:info@guiav.com.uy"><i class="fa fa-envelope-o fa-1x"></i></a></li>
								<li class="mail"><a href="https://twitter.com/GuiavUruguay"><i class="fa fa-twitter fa-1x"></i></a></li>
							</ul>
							<br>
							<p>info@guiav.com.uy<br>(+598) 2203 9897<br>

							Av. Agraciada 2541 Of. 101<br>
							Montevideo, Uruguay</p>


					</div>
					<div id="auspicios">
						<h4>Auspician:</h4>
						<ul>
							<li><a href="http://www.mgap.gub.uy" target="_blank"><%= image_tag "ministerio.jpg" , height: '45' %></a></li>
							<li><a href="http://www.smvu.com.uy/" target="_blank"><%= image_tag "smvu.jpg" , height: '45' %></a></li>
						</ul>
						<br>
					</div>
				</div>
				<div id="arrow-up">
					<a href="#"><i class="fa fa-arrow-circle-up fa-4x"></i></a>
				</div>
			</div>
		</div>
		<div class="copyright">
			<p class="copy">© 2014 GuiaV Uruguay. All rights reserved. Developed by <a href="http://jetlabs.github.io" target="_blank"><%= image_tag "jetlabs_logo.png" , height: '18', style: "margin-top:-4px;"  %></a></p>
		</div>

	
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

	<!-- EL RUBY EMBED NO ESTA EN BLANCO !!!! -->	
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    
</body>
</html>

app/views/layouts/nav.html.erb
<!DOCTYPE html>
<html ng-app="guiaV">
<head>
  <title>Guia V | Vademecum Veterinario</title>

  <meta name="description" content="Vademecum de especialidades veterinarias para grandes y pequeños animales">
	<meta name="keywords" content="vademecum, veterinario, uruguay">
	<meta property="og:url" content="http://www.guiav.com.uy/" />
	<meta property="og:image" content="http://www.guiav.com.uy/images/bookit.png" />
	<meta property="og:title" content="Guia V" />
	<meta property="og:description" content="Vademecum Veterinario" />

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'icon.ico' %>

  <!-- fonts -->
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
</head>
<body>
	<div id="wrapper">
		<div id="header" class="nav">
			<%= image_tag "logochico.png" , height: '40', style: "float:left; margin-top: 10px; padding-left: 30px;" %>
			<div class="header-nav">

				<ul>
					<% if current_user %>
						<li><a href=""><%= current_user.username %></a></li>
						<li><a href="/logout">Log out</a></li>
					<% else %>
						<li><a href="">Sign up</a></li>
						<li><a href="" data-toggle="modal" data-target="#signInModal">Log in</a></li>
					<% end %>
					<li><a href="">Help &nbsp;<i class="fa fa-angle-down"></i></a></li>
				</ul>
			</div>
			<div id="licencia">
				<%= link_to 'Upgrade to GuiaV PRO Now', paypal_url, class: "btn btn-outline-inverse btn-lg", style: 'display: none' %> 
			</div>
			 
		</div>

		<!-- Modal -->
		<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" ng-controller="LogInController as loginCtrl">
		  <div class="modal-dialog">
		    <div class="modal-content">
		    	<form class="form-horizontal" role="form">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
		      </div>
		      <div class="modal-body">
		        <div ng-show="invalido" class="alert alert-danger">Usuario o contrasenia incorrecta</div>
		        <div ng-show="valido" class="alert alert-success">Bienvenido</div>
				  <div class="form-group">
				    <div class="col-sm-offset-1 col-sm-10" >
				      <input type="text" ng-model="username" class="form-control" id="inputEmail3" placeholder="Usuario">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-1 col-sm-10">
				      <input type="password" ng-model="password" class="form-control" id="inputPassword3" placeholder="Contraseña">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-2 col-sm-3">
				      <div class="checkbox">
				        <label>
				          <input type="checkbox" ng-model="remember"> Recordarme
				        </label>
				      </div>
				    </div>
				  </div>
				
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		        <button type="submit" class="btn btn-primary" ng-click="userValido()">Sign In</button>
		        
		      </div>
		      </form>
		    </div>
		  </div>
		</div>
	
		<%= yield %>

		<div class="copyright">
			<p class="copy">© 2014 GuiaV Uruguay. All rights reserved. Developed by <a href="http://jetlabs.github.io" target="_blank"><%= image_tag "jetlabs_logo.png" , height: '18', style: "margin-top:-4px;"  %></a></p>
		</div>

	<!-- EL RUBY EMBED NO ESTA EN BLANCO !!!! -->	
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    
</body>
</html>